### ISSUE TITLE
Update minimum build plugin core version in README

### ISSUE THREAD

**Issue by daniel-shuy** [societe-generale/arch-unit-maven-plugin#41]
## Summary

The [README]((https://github.com/societe-generale/arch-unit-maven-plugin#user-content-how-to-use-archunit-maven-plugin-)) still specifies the minimum `arch-unit-build-plugin-core` version as `SOME_VERSION_GREATER_THAN_2.3.0`. It should be updated to `SOME_VERSION_GREATER_THAN_2.6.0`.

Ideally the major version of the `arch-unit-build-plugin-core` should be incremented for every breaking change.

## Type of Issue

It is a : 
 - [ ] bug
 - [ ] request
 - [x] question regarding the documentation

## Your Environment

* Version used: 2.6.1

**Comment by vincent-fuchs** [comment]
well, technically, 2.6.0 is greater than 2.3.0 ;-)

That part of the documentation is a bit specific to a certain use case, so I think it makes sense to keep the reference to 2.3.0 .

I've added the Maven central badge at the top, so that we immediately see what is the latest, even if the documentation is not fully up to date in terms.

`maven-plugin ` and `core` versions are aligned : when a potentially breaking change was introduced in `core`, I upgraded the version to 2.6.x , and then did the same for `maven-plugin `.

**Comment by daniel-shuy** [comment]
What I mean is that the documentation suggests that the current version of the `maven-plugin` works with core `2.3.0` and above, when in actuality it requires at least core `2.6.0`. Maybe update the documentation to state that the `core` version needs to be higher than the `maven-plugin` version?
