### ISSUE TITLE
 @ArchTest of type ArchTests are not picked up by plugin

### ISSUE THREAD

**Issue by chtibob69** [societe-generale/arch-unit-maven-plugin#47]
## Summary
Grouped Tests of type ArchTests (instead of ArchRule) are not picked up by the maven plugin
```
@ArchTest
public static final ArchTests TESTS_SUITE = ArchTests.in(RulesLibrary.class);
```

## Type of Issue
It is a : 
 - [x ] bug

## Current Behavior

When executing this test the maven plugin do not load CODING_RULES ; only MY_RULE
```
@AnalyzeClasses(  packages = xxx,  importOptions = xxx)
public class GroupedTest {
   @ArchTest
    public static final ArchTests TESTS_SUITE = ArchTests.in(CodingRulesLibrary.class);
   @ArchTest
    public static final ArchRule MY_RULE = classes().xxx ;
}
```

## Expected Behavior

Tests inside `CodingRulesLibrary.class` must be executed

## Steps to Reproduce (for bugs)

Try to run Tests grouped with `ArchTests.in`

## Your Environment

* Version used:
* Version of libs used: archunit 0.21.0 ; maven-plugin 2.8.0

**Comment by vincent-fuchs** [comment]
can you share your plugin config please ? do you really expect the plugin to run this ? because it looks more like a regular unit test that would be run with the other tests of your projects, even without the need of the plugin.

**Comment by chtibob69** [comment]
Yes, it is regular unit test
And I just try to use the plugin to run it : so it can be shared across all the projects
Why just picking ArchRule and not ArchTests too ?

**Comment by vincent-fuchs** [comment]
Unlike ArchRule, ArchTests is part of archunit-junit5-api jar - not archunit "core" jar.

We are not using ArchTests for now, and I am afraid doing so would make the API and config more verbose and/or require a major refactoring. an ArchTests is just a collection of rules, isn't it ? it would be a bit more verbose to list the rules in the current config, but it would work, wouldn't it ?  

Feel free to investigate and propose a way this could work, because I don't think I'll do it myself.

**Comment by chtibob69** [comment]
Yes, it would work
I understand
Thanks for the reply
